### ISSUE TITLE
updating state

### ISSUE THREAD

**Issue by cjessett** [tina-pina/jamming#3]
(Important) [Here](https://github.com/tina-pina/jamming/blob/b99a861e787bcea61fda576e5c2bf40b2927c876/src/Components/App/App.js#L28) instead of modifying state directly with `.push`, create a new array with the desired state and use `.setState` to update state with the new array. The React docs specifically warn against modifying state directly, which is what `.push` is doing here since it changes and array in place.

**Comment by tina-pina** [comment]
Thank you for the feedback.
